services:
  postgres:
    image: postgres:16-alpine
    container_name: pagboleto-postgres
    environment:
      POSTGRES_DB: pagboleto
      POSTGRES_USER: pagboleto
      POSTGRES_PASSWORD: pagboleto
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pagboleto"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: pagboleto-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: pagboleto
      RABBITMQ_DEFAULT_PASS: pagboleto
    ports:
      - "5672:5672"
      - "15672:15672" # http://localhost:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
    pgdata:
