// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PagBoleto.Infrastructure.Persistence;

#nullable disable

namespace PagBoleto.Infrastructure.Migrations
{
    [DbContext(typeof(PagBoletoDbContext))]
    partial class PagBoletoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PagBoleto.Domain.Entities.Boleto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("LinhaDigitavel")
                        .IsRequired()
                        .HasMaxLength(54)
                        .HasColumnType("character varying(54)")
                        .HasColumnName("linha_digitavel");

                    b.Property<string>("MotivoFalha")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_falha");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TentativasProcessamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tentativas_processamento");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date")
                        .HasColumnName("vencimento");

                    b.HasKey("Id");

                    b.HasIndex("LinhaDigitavel")
                        .IsUnique()
                        .HasDatabaseName("ix_boletos_linha_digitavel");

                    b.HasIndex("Status", "Vencimento")
                        .HasDatabaseName("ix_boletos_status_vencimento");

                    b.ToTable("boletos", (string)null);
                });

            modelBuilder.Entity("PagBoleto.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ProcessadoEm", "CriadoEm")
                        .HasDatabaseName("ix_outbox_message_processado_criado_em");

                    b.ToTable("outbox_messages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
